### ISSUE TITLE
Replace Loomio image on Badge Epicenter page

### ISSUE THREAD

**Issue by dajbelshaw** [weareopen/AllTheThings#21]
Let's use the image from this page to differentiate: https://www.shareable.net/blog/5-group-decision-making-resources-from-loomio

Page: http://weareopen.coop/badges

We could have a little Badge Wiki logo in the bottom-right?

**Comment by LauraHilliger** [comment]
https://github.com/weareopen/weareopen.github.io/commit/e7fa17c631ef42c144a964568d131c32c40ba801
