### ISSUE TITLE
Find portfolio style template for new WAO website design

### ISSUE THREAD

**Issue by LauraHilliger** [weareopen/AllTheThings#24]
consider WP too...

@dajbelshaw - why didn't we WP at the beginning, just out of curiosity?

**Comment by LauraHilliger** [comment]
https://gohugo.io/

**Comment by dajbelshaw** [comment]
We didn't want to pay for hosting, and we wanted everyone to be able to contribute easily (so we went with GitHub Pages)

**Comment by LauraHilliger** [comment]
https://themes.gohugo.io/theme/hugo-icon/
https://themes.gohugo.io/theme/hugrid/
https://themes.gohugo.io/theme/artists/

three themes I can imagine for our new content @bryanmathers

**Comment by LauraHilliger** [comment]
@dajbelshaw Have you used Hugo before? I installed it in a subfolder and started tinkering, but I spent a couple hours and am not satisfied with productivity. Think it might be easier to do a static site. Thoughts?

https://github.com/weareopen/weareopen.github.io/tree/master/oct2017
