### ISSUE TITLE
Create a draft website

### ISSUE THREAD

**Issue by bryanmathers** [weareopen/AllTheThings#39]
Decide on a suitable platform and put together a skeleton site reflecting the new design elements, but also incorporating the current content.

**Comment by dajbelshaw** [comment]
I'd separate this out as two issues:

1. Decide on suitable platform 
2. Put together skeleton site

Why? Because then we can have discussions about container separate from (style and) content.

**Comment by bryanmathers** [comment]
Done - see issue #45

**Comment by LauraHilliger** [comment]
this is at staging, i'd say it's drafty: http://weareopen.coop/staging/
