### ISSUE TITLE
Decide which platform to use for the WAO website

### ISSUE THREAD

**Issue by bryanmathers** [weareopen/AllTheThings#45]
# Criteria
Here are some initial criteria:
- Updating the dynamic content is a simple process and doesn't require techie skills
- The website supports being updated by any co-op member
- People can find it - search engine friendly code
- It's design is Responsive - but prioritises mobile display
- We're able to utilise some out-of-the-box stuff that already exists (themes / widgets / libraries) so that we don't have to reinvent the wheel)
- We have enough granular control - so if we can go off-piste if need be.
- We currently have the skills to build and maintain it.

**Comment by LauraHilliger** [comment]
@dajbelshaw @bevangelist we decided to use Jekyll, fyi. Let us know if you hate that decision, but Bryan and I think this is a good solution.

**Comment by bryanmathers** [comment]
Lovely. Done.
