### ISSUE TITLE
Submit paper to co-op college conf

### ISSUE THREAD

**Issue by LauraHilliger** [weareopen/AllTheThings#46]
**DUE February 14**

https://www.co-op.ac.uk/news/co-operative-education-and-research-conference-2018-call-for-papers

**Comment by LauraHilliger** [comment]
What about applying to Strand 2b with an expansion on:

_According to the International Co-operative Alliance:

A co-operative is an  autonomous association of persons united voluntarily to meet their  common economic, social, and cultural needs and aspirations through a  jointly-owned and democratically-controlled enterprise.

Let's do a little remix:

The Commons are artefacts openly licensed by an autonomous association of persons. They use open licensing to meet their common economic, social, and cultural needs and aspirations through a jointly-owned and democratically-controlled system of resources.

The Co-op movement and the Open movement have more than a little in common, yet they are tenuously connected through individuals rather than entire communities. In this session, we try to figure out how to change that._

**Comment by dajbelshaw** [comment]
For context, here's what we presented last year:

* https://goo.gl/XzLWso
* https://goo.gl/n5TZGK

Both sessions were pretty well-attended.

**Comment by LauraHilliger** [comment]
I'm still fiddling with this. Have a train ride tomorrow and will finish up then (it's sunny and I want to go outside)
https://docs.google.com/document/d/1qqxNpIPXVdTe3PJk1iHvCDcVCPtg-3K4nU_OnEVdLZM/edit#
