### ISSUE TITLE
install jekyll

### ISSUE THREAD

**Issue by LauraHilliger** [weareopen/AllTheThings#47]
Install jekyll into a subfolder in the WAO website

**Comment by dajbelshaw** [comment]
What's the context here. Why Jekyll instead of, for example, [Hugo](https://gohugo.io/)?

**Comment by LauraHilliger** [comment]
I tried Hugo last year and wasn't successful with it. I just realized the ticket is still open: https://github.com/weareopen/AllTheThings/issues/24

**Comment by dajbelshaw** [comment]
OK

**Comment by LauraHilliger** [comment]
Heyo I installed Jekyll and started tinkering, even building a little. It's in the /materialize folder and is using Material CSS. 

https://github.com/weareopen/weareopen.github.io/commit/54c82a3789c3608d19fc415bfd0c4fc7e8d58621

@bryanmathers how would you feel about using colors from the color palette here? Would just save us from redefining the default materialize colors (of which there are many):

http://materializecss.com/color.html

![image](https://user-images.githubusercontent.com/539017/35986386-2feebd48-0cf9-11e8-93f7-26d8ace99931.png)
