### ISSUE TITLE
Set Paddy McPadface to be on https

### ISSUE THREAD

**Issue by LauraHilliger** [weareopen/AllTheThings#50]
Is this possible with little to no cost @bryanmathers ? Came up in the cotech call....

**Comment by bryanmathers** [comment]
No idea - I'll take a look.

**Comment by georgeowell** [comment]
You can use [LetsEncrypt](https://letsencrypt.org/) via [Certbot](https://certbot.eff.org/) to get a free cert. Let me know if you need any help with that.

**Comment by dajbelshaw** [comment]
We also need our main site to be on https, right?

**Comment by georgeowell** [comment]
I would recommend using https on all your infrastructure. Let me know if you need any help or advice.

Some background to why https is importantr: https://www.eff.org/encrypt-the-web

**Comment by bryanmathers** [comment]
after armwrestling with linux, etherpad is now running on https...

and so is the website. :)
