### ISSUE TITLE
Write the benefits of membership (logistical benefits)

### ISSUE THREAD

**Issue by LauraHilliger** [weareopen/AllTheThings#60]
we need write up the benefits of membership, we started this somewhere, maybe in person co-op day.

Will need to document 

What else:  
Monday meetings
Interaction on 'members' Slack channel
Voting on Loomio
In-person meetups
Admin access to trello, github, calendar, etc

**Comment by LauraHilliger** [comment]
http://pads.weareopen.coop:9001/p/may-2018

**Comment by bevangelist** [comment]
Started the list at bottom of https://github.com/weareopen/AllTheThings/wiki/Co-op-Membership

Add things I've missed or drop in a comment here and I'll do so.

**Comment by ghami** [comment]
I added in a section on becoming a partner at bottom of Membership page on wiki. It's a starter for 10 and best guess on what this might mean! Haven't changed the title of the page to include that as it would be good to get feedback on whether it should be a separate page or not. https://github.com/weareopen/AllTheThings/wiki/Co-op-Membership
