### ISSUE TITLE
Fix the swipe carousel on the new website

### ISSUE THREAD

**Issue by LauraHilliger** [weareopen/AllTheThings#61]
The carousel on http://weareopen.coop/staging/what/ 
is supposed to be touch compatible. Doesn't work on my android though, which means you can scroll through our 3 areas of work. Maybe @bryanmathers can figure it out?

If not, we should probably rewrite that page completely :(

We're so close to being able to launch this!

**Comment by bryanmathers** [comment]
We ditched the carousel - as it looked like there were a few other glitches to it...
