### ISSUE TITLE
Check staging site meets accessibility guidelines

### ISSUE THREAD

**Issue by dajbelshaw** [weareopen/AllTheThings#69]
Several ways of checking this, including the [IDI Web Accessibility Checker](https://achecker.ca/checker/index.php)

**Comment by LauraHilliger** [comment]
fixed https://github.com/weareopen/weareopen.github.io/commit/1a85ef7c91637121562b7a31380d13ec47801174

1.4 and 4.1 are not relevant, but the rest is fixed.
