### ISSUE TITLE
Nav hits logo on a certain screen size

### ISSUE THREAD

**Issue by bryanmathers** [weareopen/AllTheThings#78]
<img width="755" alt="screen shot 2018-05-18 at 17 34 19" src="https://user-images.githubusercontent.com/4199961/40246751-c8a9f32a-5ac1-11e8-934f-d54c44628af1.png">

**Comment by LauraHilliger** [comment]
I put in a fix for this, but I don't think it's 100%. It's certainly better, but I just used the grid and the btn drops at a certain point. Don't have time at the moment to look into it further so I pushed the partial fix.

**Comment by bryanmathers** [comment]
No worries. Well now, it seems that Chrome displays the nav text in a larger size than FF. So in Chrome the problem is much more pronounced.

I came to the conclusion that it's probably a design issue - not a programming one...

**Comment by bryanmathers** [comment]
I get it now - I thought I'd been seeing things! However, I realise now that I was looking at the staging site - which seems to have the larger Nav text for some reason. I was looking at the lovely new Thinkathon page you made. We need to make sure that by putting staging live, it doesn't overwrite the fix you've already added...
