### ISSUE TITLE
make a new thinkathon page

### ISSUE THREAD

**Issue by LauraHilliger** [weareopen/AllTheThings#79]
@dajbelshaw said people loved the thinkathon page and he wishes it still existed. So let's make one.

**Comment by LauraHilliger** [comment]
@bryanmathers I made this on staging, removed redirects, etc. But before I put it on production I need graphics (these are the ones from the Join page). Instead of making new ones, let's choose from stuff you've already done?

http://weareopen.coop/staging/thinkathon/

**Comment by LauraHilliger** [comment]
please file new tickets for changes!

**Comment by bryanmathers** [comment]
Nice work!

**Comment by dajbelshaw** [comment]
This is great! Could we move it to production? :+1:
