### ISSUE TITLE
Decide what we're going to *make* at our July 2018 meetup

### ISSUE THREAD

**Issue by dajbelshaw** [weareopen/AllTheThings#81]
In our agenda, we've got a line about focusing on *making* something (given all the previous meta conversations we've had at our meetups).  

http://pads.weareopen.coop:9001/p/july18-meetup

Things that have been suggested:

- something about Offline vs Online Communities
- all the things

**Comment by bryanmathers** [comment]
What about a paper prototype of what a portfolio of badges would look like?

**Comment by dajbelshaw** [comment]
@bryanmathers Do you mean in terms of  something we could build?

**Comment by bryanmathers** [comment]
Yes - it's just a suggestion though. I'm interested in developing _helper_ tools that don't constitute a platform in themselves, but are sticky and help us win consultancy business.
