### ISSUE TITLE
sort out the 3 umbrellas buttons on the home page

### ISSUE THREAD

**Issue by LauraHilliger** [weareopen/AllTheThings#91]
basically, fix the work page still, you can't get rid of it but use your brain

**Comment by LauraHilliger** [comment]
Well, I thought I made the work page look good enough to add back to the navigation: 
https://weareopen.coop/work/

We can revisit the icons. If there is one you especially hate, please file a ticket. 

I used Materialize icons. I tried a few pieces and parts from @bryanmathers drawings while making this, but it was too much. If you're keen to do icons, I'd recommend keeping them super simple (we can also look at other icon libraries like thenounproject.com)

**Comment by bryanmathers** [comment]
Can I suggest changing the colour of the "workshops" "thinkathons" "strategy" etc to something like #e14400 (orange) or a grey or something? this might well separate the big header sentence and the paragraphs of text and make it more readable. (maybe!) Just a thought...
